<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="environment" nsURI="http://www.example.org/environment" nsPrefix="environment">
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalAsset" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedAssets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAsset" eType="#//PhysicalAsset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputingDevice" eSuperTypes="#//PhysicalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="ON"/>
    <eLiterals name="OFF" value="1"/>
    <eLiterals name="BROKEN" value="2"/>
    <eLiterals name="UNKOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HVAC" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmartLight" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Laptop" eSuperTypes="#//Computer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Desktop" eSuperTypes="#//Computer"/>
  <eClassifiers xsi:type="ecore:EClass" name="CCTV" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="#//Computer"/>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//DigitalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//FileStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//DigitalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//DigitalStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//DigitalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//DigitalStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DigitalStatus">
    <eLiterals name="RUNNING"/>
    <eLiterals name="NOT_RUNNING" value="1"/>
    <eLiterals name="SUSPENDED" value="2"/>
    <eLiterals name="UNKNOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FileStatus">
    <eLiterals name="OPEN"/>
    <eLiterals name="CLOSED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true">
    <eOperations name="similarTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="connection" eType="#//Connection"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset1" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset2" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidirectional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerabilities" upperBound="-1"
        eType="#//Vulnerability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalConnection" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true">
    <eOperations name="abstractAsset" eType="#//Asset"/>
    <eOperations name="similarTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="asset" eType="#//Asset"/>
    </eOperations>
    <eOperations name="mergeConnections"/>
    <eOperations name="canMergeConnections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="canMergeContainedAssets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="mergeContainedAssets"/>
    <eOperations name="mergeConnections" unique="false">
      <eParameters name="connections" upperBound="-1" eType="#//Connection"/>
    </eOperations>
    <eOperations name="canMergeConnections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="connections" upperBound="-1" eType="#//Connection"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="control" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerabilities" upperBound="-1"
        eType="#//Vulnerability"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobility" eType="#//Mobility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//Port"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" upperBound="-1"
        eType="#//Credential" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" upperBound="-1"
        eType="#//Credential" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CredentialType"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="other" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//PhysicalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalStructure" eSuperTypes="#//PhysicalAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalAsset" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAsset" eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedAssets" upperBound="-1"
        eType="#//DigitalAsset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preconditions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postconditions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//PhysicalStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Floor" eSuperTypes="#//PhysicalStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//PhysicalStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="FireAlarm" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workstation" eSuperTypes="#//Computer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lab" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="Toilet" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lounge" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="DishWasher" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoffeeMachine" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Elevator" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hallway" eSuperTypes="#//PhysicalStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElevatorsArea" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPNetwork" eSuperTypes="#//DigitalNetwork"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalNetwork" eSuperTypes="#//DigitalAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encryption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusNetwork" eSuperTypes="#//DigitalNetwork"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPConnection" eSuperTypes="#//DigitalConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusConnection" eSuperTypes="#//DigitalConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kitchen" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stairs" eSuperTypes="#//PhysicalStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="CardReader" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Visitor" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CredentialType">
    <eLiterals name="PASSWORD"/>
    <eLiterals name="PINCODE" value="1"/>
    <eLiterals name="CARD" value="2"/>
    <eLiterals name="FINGERPRINT" value="3"/>
    <eLiterals name="OTHER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedComputer" eSuperTypes="#//Computer"/>
  <eClassifiers xsi:type="ecore:EClass" name="MicroController" eSuperTypes="#//EmbeddedComputer"/>
  <eClassifiers xsi:type="ecore:EClass" name="WiredConnection" eSuperTypes="#//PhysicalConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ethernet" eSuperTypes="#//WiredConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Walkway" eSuperTypes="#//PhysicalConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="KNX" eSuperTypes="#//BusConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="X10" eSuperTypes="#//BusConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vulnerability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Level">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="UNKNOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Office" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmartTV" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="AccessPoint" eSuperTypes="#//ComputingDevice"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Mobility">
    <eLiterals name="MOVABLE"/>
    <eLiterals name="FIXED" value="1"/>
    <eLiterals name="UNKNOWN" value="2"/>
  </eClassifiers>
</ecore:EPackage>
